### Transforming code into idiotic python
- Replace traditional index manuolation with python core looping Idiomatic

In [5]:
# looping over a range of numbers- traditional Approach
for i in [0,1,2,3,4,5]:
 print(i**2,end=" ")

0 1 4 9 16 25 

In [6]:
#Idiomatic programming
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

### looping over a collection

In [7]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [8]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### looping backwards

In [9]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [10]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

## looping in sorted oder

In [16]:
colors = ['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

In [17]:
colors =['red','green','yellow','purple']
for color in sorted(colors,reverse = True):
    print(color,end=" ")

yellow red purple green 

In [18]:
### 
- if x <= y and y <=z
- if

SyntaxError: invalid syntax (<ipython-input-18-d3a2e278f001>, line 2)

### Pandas

In [20]:
import pandas as pd

In [26]:
dt = {'Id':[11,12,13,14,15],
      'first_name':['A','B','C','D','E'],
      'company':['aa','bb','cc','dd','ee'],
      'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [27]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [28]:
import os

In [39]:
os.chdir(r"D:\softwares")# saves to certain location

In [40]:
mydt.to_csv('workingFile.csv',index = False)

### Reading the Data from Csv File

In [41]:
mydata = pd.read_csv('workingFile.csv')

In [42]:
mydata

Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd

In [43]:
mydata = pd.read_csv('workingFile.csv',skiprows=1,
                    names=["custId","name","company","Address"])

In [44]:
print(mydata)

   custId name company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


## print the large value from custID column -- Max
## print the large value from custID column -- min


### Numpy Package
- Numpy arrays are bit like python list
- Numpy is also one od data structure
- Numpy short name for "Numerical python"

In [45]:
import numpy as np # import the numpy package

In [46]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [47]:
array = np.array(li) # convert the list into array using np.array(li)
print(array)

[1 2 3 4 5]


In [48]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [49]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [51]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
